=== farhathjaha/EP-SKILLING/EPSKILL-7-1-21/WebContent/task-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="Students">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="student" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="student">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="no" />
				<xs:element ref="name" />
				<xs:element ref="email" />
				<xs:element ref="marks" />
				<xs:element ref="class" />
			</xs:sequence>
			<xs:attribute name="sid" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="no" type="xs:integer" />
	<xs:element name="name" type="xs:string" />
	<xs:element name="email" type="xs:string" />
	<xs:element name="marks" type="xs:integer" />
	<xs:element name="class" type="xs:NCName" />
</xs:schema>

=== farhathjaha/EP-SKILLING/EPSKILL-7-1-21/WebContent/Task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="task-3.xsd">

	<student sid="a">
		<no>190031491</no>
		<name> SHAIK FARHATH JAHA</name>
		<email>farhathjaha@gmail.com</email>
		<marks>100</marks>
		<class>section-1</class>
	</student>
	<student sid="b">
		<no>190031492</no>
		<name> VEDA SREE</name>
		<email>vs@gmail.com</email>
		<marks>98</marks>
		<class>section-2</class>
	</student>
	<student sid="c">
		<no>190031493</no>
		<name> PRAGATHI CHAWDARY</name>
		<email>pc@gmail.com</email>
		<marks>96</marks>
		<class>section-3</class>
	</student>
	<student sid="d">
		<no>190031496</no>
		<name> DEEPIKA</name>
		<email>fdeepu@gmail.com</email>
		<marks>99</marks>
		<class>section-1</class>
	</student>
	<student sid="e">
		<no>190031497</no>
		<name> BHAVANA</name>
		<email>baavs@gmail.com</email>
		<marks>100</marks>
		<class>section-1</class>
	</student>
	<student sid="f">
	    <no>190031498</no>
		<name> HARSHITHA</name>
		<email>Harshi@gmail.com</email>
		<marks>89</marks>
		<class>section-4</class>
	</student>
</Students>
